spring:
  application:
    name: task-service
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083
  
logging:
  level:     
    com.diagonal.taskervice: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/